### PR TITLE
change the default value of payload

### PR DESCRIPTION
**Pull request by gainskills**
For the restlet which doesn't require a param, otherwise, netSuite returns 400 error:
```
Body: {"error" : {"code" : "SYNTAX_ERROR", "message" : "SyntaxError: Empty JSON string (null$lib#3)."}}
```

Note: I have enabled trim space and auto format on my IDE which causes many differences.

### CODE REVIEW

**Comment by tho-can-code** [comment]
Hi @gainskills, would you please update this package to work with version 2019_2_0? Currently it's version is 2018_1_0.

**Comment by gainskills** [comment]
Hi @thosieucoi,  this change is for restlet, it works with 2019_2_0.

**Comment by tho-can-code** [comment]
Hi @gainskills, when I try to changed
`version = '2018.1.0'` in client.py (line 92)
to `version = '2019.2.0'`
it throws the error when call.
Would you please check it?

**Comment by gainskills** [comment]
Let me see what I can do on the new version...

**Comment by jjorissen52** [comment]
Please open an issue dedicated to this feature request and continue further
discussion there.

**Comment by tho-can-code** [comment]
Hi @jjorissen52, would you please recheck on restlet?
I try to call restlet and got the error
`requests.exceptions.HTTPError: 403 Client Error: Forbidden`

**Comment by tho-can-code** [comment]
Also, in your README
`import netsuite.restlet as nsRestlet

config = netsuite.config.from_ini()
client = nsRestlet(config=config)`

This will throw error
`TypeError: 'module' object is not callable`

**Pull request merged**
